server:
  port: 8765

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive  # Ensure Reactive Web Application Type

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackUri: forward:/userServiceFallback

        - id: contact-service
          uri: lb://CONTACT-SERVICE
          predicates:
            - Path=/contact/**
          filters:
            - name: CircuitBreaker
              args:
                name: CONTACT-SERVICE
                fallbackUri: forward:/contactServiceFallback

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMillieseconds: 5000




management:
  endpoints:
    web:
      exposure:
        include: "*" # To expose all Actuator endpoints (optional)
  endpoint:
    gateway:
    enabled: true
